RNTA + CI (#642)
* baseline: adding RNTA vanilla, it works

* wire in the babylon stuff

* a couple of temp files

* minor cleanup, bump to latest 73 and RNTA

* add a quick readme

* Update Apps/BRNPlayground/macos/Podfile

Co-authored-by: Tommy Nguyen <4123478+tido64@users.noreply.github.com>

* Update Apps/BRNPlayground/postinstall.js

Co-authored-by: Tommy Nguyen <4123478+tido64@users.noreply.github.com>

* Update Apps/BRNPlayground/.gitignore

Co-authored-by: Tommy Nguyen <4123478+tido64@users.noreply.github.com>

* get CMake to build

* add xcworkspace

* bump to latest RN and RNTA

* RNTA + CI

* npm install

* java 17 instead of 21(default) because of this issue:
 jdk.tools.jlink.plugin.PluginException: ModuleTarget is malformed: platformString missing delimiter: android

* Windows build

* npm install package

* msbuild typo

* more windows build steps

* build steps in CI

* path typo

* nuget restore

* BN build

* vcxproj paths

* x86

* back to x64

* test w/o  --use-nuget

* patch rnpermissions vcxproj

* back with use-nuget

* permissions vcxproj

* vcxproj

* packages.config

* cppwinrt

* merge .sln

* do not build bundle

* props test

* import path

* props path again

* put back libs in

* cppwinrt

* cmake import props

* project imports

* windows sdk props

* windows sdk version

* bump rn permissions

* cleaning

* bundle build

* ios/android builds

* windows build debug

* nuget

* nuget

* metro config test

* watchman

* choco watchman

* is this useful?

* up rnta

* artifact test

* ios/android

* build output dir

* clean up

* build windows

* build fixes

* windows build/cppwinrt

* kick build

---------

Co-authored-by: Lorenzo Sciandra <lsciandra@microsoft.com>
Co-authored-by: Lorenzo Sciandra <lorenzo.sciandra@gmail.com>
Co-authored-by: Tommy Nguyen <4123478+tido64@users.noreply.github.com>